version: '3'
services:
  dshield-connector:
    image: ghcr.io/robinzor/opencti-dshield:main
    container_name: connector-dshield
    restart: unless-stopped
    environment:
      - OPENCTI_API_URL=${OPENCTI_API_URL}
      - OPENCTI_API_KEY=${OPENCTI_API_KEY}
      - OPENCTI_VERIFY_SSL=${OPENCTI_VERIFY_SSL:-false}
      - DSHIELD_INTERVAL=${DSHIELD_INTERVAL:-300}
      - DSHIELD_UPDATE_EXISTING_DATA=${DSHIELD_UPDATE_EXISTING_DATA:-true}
      - DSHIELD_CONFIDENCE_LEVEL=${DSHIELD_CONFIDENCE_LEVEL:-60}
      - DSHIELD_UPDATE_FREQUENCY=${DSHIELD_UPDATE_FREQUENCY:-300}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 