version: '3'
services:
  connector:
    build: .
    environment:
      - OPENCTI_API_URL=http://opencti:8080
      - OPENCTI_API_KEY=${OPENCTI_API_KEY}
      - OPENCTI_VERIFY_SSL=false
      - CONFIDENCE_LEVEL=60
      - UPDATE_EXISTING_DATA=false
      - UPDATE_FREQUENCY=30
    restart: always
  urlscan-connector:
    image: ghcr.io/robinzor/opencti-urlscan:main
    container_name: connector-urlscan
    restart: unless-stopped
    environment:
      - OPENCTI_API_URL=${OPENCTI_API_URL}
      - OPENCTI_API_KEY=${OPENCTI_API_KEY}
      - OPENCTI_VERIFY_SSL=${OPENCTI_VERIFY_SSL:-false}
      - INTERVAL=${INTERVAL:-300}
      - UPDATE_EXISTING_DATA=${UPDATE_EXISTING_DATA:-true}
      - CONFIDENCE_LEVEL=${CONFIDENCE_LEVEL:-60}
      - UPDATE_FREQUENCY=${UPDATE_FREQUENCY:-300}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 